### ISSUE TITLE
[Improvement] Pass parameters to JSON pastas

### ISSUE THREAD

**Issue by ldelelis** [tadeokondrak/ArchBot#8]
Example: the old !interject command.

**Comment by tadeokondrak** [comment]
Yes! I have an idea of how to do this:

!interject find/replace find/replace

and it would find and replace each pair

**Comment by ldelelis** [comment]
I'll get on it. If it works it could be implementable to !stfu too.

**Comment by nhatzHK** [comment]
I did that this morning. Very easy to implement.
